@startuml sic_status_message
actor Usuario
participant Frontend
participant Backend
participant SicStatusController
participant .env

== Envío de datos al controlador ==
Usuario -> Frontend : Ingresar datos
Frontend -> Backend : POST /sic_status_message()
Backend -> SicStatusController : sic_status_message()
SicStatusController -> .env : busca la variable de entorno\nESTADO_MSJ_SIC
.env --> SicStatusController : retorna valor de la variable
alt Es true
  SicStatusController -> .env : busca la variable de entorno\nMENSAJE_SIC
  .env --> SicStatusController : retorna valor de la variable
else Es false
  SicStatusController -> SicStatusController : retorna vacío
end

== Responder al cliente ==
SicStatusController -> Backend : respuesta final
Backend -> Frontend : respuesta al usuario
Frontend -> Usuario : mostrar respuesta
@enduml
